# Validate with http://lint.travis-ci.org/
sudo: required
language: node_js
node_js: "6.1"

install:
  - cd ignite-base
  - npm install --no-progress
script:
  - npm test
  - cd ..
  - ./fireDrill.sh
